name: Build Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Change this if needed

      - name: Install dependencies
        run: cd signup && npm install

      - name: Lint (optional)
        run: cd signup && echo "No linter configured yet"

      - name: Docker Build
        run: docker build -t my-node-app ./signup

      - name: Docker Compose Up (optional)
        run: docker-compose -f signup/docker-compose.yml up -d
