name: Build Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Change this if you use a different version

      - name: Install dependencies
        run: npm install

      - name: Lint (optional)
        run: |
          echo "Skipping lint. Add ESLint or similar if needed."

      - name: Docker Build
        run: docker build -t my-node-app .

      - name: Docker Compose Up (optional)
        run: docker-compose up -d
